apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: c1-juice-shop
  labels:
    app: c1-juice-shop
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: juice-shop
    targetPort: 3000
  selector:
    app: c1-juice-shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: c1-juice-shop
  name: c1-juice-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c1-juice-shop
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: c1-juice-shop
    spec:
      containers:
      - name: c1-juice-shop
        image: $K8S_REGISTRY/c1-juice-shop:latest
        imagePullPolicy: Always
        env:
        - name: TREND_AP_KEY
          value: 325a65a5-03ba-4095-8a99-a4486fad6ef6
        - name: TREND_AP_SECRET
          value: 0bf41ec4-5c36-4dcd-9db9-53fc7e384fb4
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
